data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/GCP/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'airflow-bigquery-dbt-soda'
    dataset: retail
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: f053bba9-1a10-47d9-a766-8a7b0ff84902
  api_key_secret: VKdmOVHM7WV8k8yWY6K9aoFah-8GggBr23HKW1SQs-bJbyIzy6rPuA